title: CTML OTMLE <br>Reading Group
description: Wednesdays 2-4PM PT, BWW TBD
show_downloads: false
google_analytics: 
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
github:
  is_project_page: false